<div class="col-xs-12">
    <?=$this->FlashMessenger(); ?>
    <div class="well">
        <div class="form-group">
            <label for="login" class="control-label">Email</label>
            <input type="text" class="form-control" id="login" name="email" title="Digite seu nome de usuário" placeholder="exemplo@seudominio.com">
            <span class="help-block"></span>
        </div>
        <div class="form-group">
            <label for="password" class="control-label">Senha</label>
            <input type="password" class="form-control" id="password" name="senha">
            <span class="help-block"></span>
        </div>
        <div id="loginErrorMsg" class="alert alert-error hide"></div>

        <button type="button" class="btn btn-success btn-block login">Login</button>
        <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'cadastro'), null, true); ?>" class="btn btn-primary btn-block">Não sou cadastrado</a>
    </div>
</div>
