<div class="col-xs-12">
    <div class="well">
        <div id="loginForm">
            <div class="form-group">
                <input type="hidden" class="form-control" id="item" name="item" value="<?= $this->item; ?>">
                <input type="hidden" class="form-control" id="cliente" name="cliente" value="<?= $this->cliente; ?>">
                <div class="form-group">
                    <label for="comment">Faça sua proposta:</label>
                    <textarea class="form-control" rows="5" name="proposta" required="requerid" id="proposta"></textarea>
                </div>
                <span class="help-block"></span>
            </div>
            <button type="submit" id="envia_proposta" class="btn btn-success btn-block">Enviar Proposta</button>
        </div>
    </div>
</div>
