<table align="center" border="0" cellpadding="0" cellspacing="0" style="width:650px">
   <tbody>
      <tr>
         <td>
            <table border="0" cellpadding="0" cellspacing="0" style="width:100%">
               <tbody>
                  <tr>
                     <td style="width:148px">
                       <img src="http://<?php echo $_SERVER['HTTP_HOST'];?>/imagens/email-aniversario/1.png" border="0" alt="" style="display:block;">
                     </td>
                     <td style="background-color:rgb(121, 161, 145); width:354px">
                        <img src="http://<?php echo $_SERVER['HTTP_HOST'];?>/assets/images/logo.png" alt="" width="130" height="46" style="display:block;" border="0">
                     </td>
                     <td style="width:148px">
                       <img src="http://<?php echo $_SERVER['HTTP_HOST'];?>/imagens/email-aniversario/3.png" border="0" alt="" style="display:block;">
                     </td>
                  </tr>
               </tbody>
            </table>
         </td>
      </tr>
      <tr>
         <td  valign="top" bgcolor="#FDF2F4">
            <table border="0" cellpadding="0" cellspacing="0" style="width:100%">
               <tbody>
                  <tr>
                     <td valign="top" style="width:112px">
                        <img src="http://<?php echo $_SERVER['HTTP_HOST'];?>/imagens/email-aniversario/4.png" border="0" alt="" style="display:block;">
                     </td>
                     <td valign="top">
                        <table border="0" cellpadding="0" cellspacing="0" style="width:100%">
                           <tbody>
                              <tr>
                                 <td>
                                    <img src="http://<?php echo $_SERVER['HTTP_HOST'];?>/imagens/email-aniversario/5.png" border="0" alt="" style="display:block;">
                                 </td>
                              </tr>
                              <tr>
                                 <td height="50" style="height:50px;background-color:rgb(216, 201, 132);font-family:Arial;font-size:35px;font-weight:bold;color:#B35B38;text-align:center;">Feliz Anivers&aacute;rio!</td>
                              </tr>
                              <tr>
                                 <td>
                                    <img src="http://<?php echo $_SERVER['HTTP_HOST'];?>/imagens/email-aniversario/6.png" border="0" alt="" style="display:block;">
                                 </td>
                              </tr>
                              <tr>
                                <td style="font-family:Arial;font-size:16px;color:#CB8D75;padding-top:15px;" valign="top">
                                  <p>Ol&aacute; <?php echo utf8_decode($this->dados['nome']); ?>,</p>
                                    <p>Feliz Anivers&aacute;rio!</p>
                                   <p><br>
                                      Aceite nossos votos de um dia perfeito. Que todos seus sonhos se realizem hoje, com maior ou menor esfor&ccedil;o, e que todas as energias positivas invadam o seu dia. <br>
                                      <br>
                                      &Eacute; muito importante para nosso espa&ccedil;o receber um cliente t&atilde;o distinto como voc&ecirc;. &Eacute;, na verdade, um privil&eacute;gio, contar com sua presen&ccedil;a para aprecia&ccedil;&atilde;o de quaisquer produtos &aacute; sua disposi&ccedil;&atilde;o. Nossas portas estar&atilde;o sempre abertas para a receber.<br>
                                      <br>
                                      Tenha um dia de paz!
                                  </p>
                                 </td>
                              </tr>
                           </tbody>
                        </table>
                     </td>
                     <td  valign="top" style="width:126px">
                        <img src="http://<?php echo $_SERVER['HTTP_HOST'];?>/imagens/email-aniversario/7.png" border="0" alt="" style="display:block;">
                     </td>
                  </tr>
               </tbody>
            </table>
         </td>
      </tr>
      <tr>
         <td bgcolor="#FDF2F4" align="center" style="padding:10px;">
            <img src="http://<?php echo $_SERVER['HTTP_HOST'];?>/imagens/email-aniversario/8.png" border="0" alt="" style="display:block;">
         </td>
      </tr>
      <tr>
         <td style="background-color:rgb(121, 161, 145)">
            <table align="right" border="0" cellpadding="0" cellspacing="0" style="width:510px">
               <tbody>
                  <tr>
                     <td style="color:#406958;font-family:arial;font-size:14px;"><span style="color:#406958;">
                       <a href="http://<?php echo $_SERVER['HTTP_HOST'];?>" style="color:#406958;text-decoration:none;"><?php echo $_SERVER['HTTP_HOST'];?></a> | <span style="color:#406958;"><a href="mailto:atendimento@ravennapizzaria.com.br" style="color:#406958;text-decoration:none;">thiagocarlos@outlook.com.br</a></span></td>
                     <td style="width:79px">
                        <table border="0" cellpadding="0" cellspacing="0" style="width:69px">
                           <tbody>
                              <tr>
                                 <td>
                                    <img src="http://<?php echo $_SERVER['HTTP_HOST'];?>/imagens/email-aniversario/9.png" border="0" alt="" style="display:block;">
                                 </td>
                                 <td><img src="http://<?php echo $_SERVER['HTTP_HOST'];?>/imagens/email-aniversario/10.png" border="0" alt="" style="display:block;"></td>
                                 <td><img src="http://<?php echo $_SERVER['HTTP_HOST'];?>/imagens/email-aniversario/11.png" border="0" alt="" style="display:block;"></td>
                              </tr>
                           </tbody>
                        </table>
                     </td>
                  </tr>
               </tbody>
            </table>
         </td>
      </tr>
   </tbody>
</table>