<?
$this->headScript()->appendFile($this->BaseUrl('assets/js/mascaras.js'));
$this->headScript()->appendFile($this->BaseUrl('assets/area-cliente/js/adiciona_endereco.js'));
?>
<div id="body-container">
    <div id="body-content">
        <?= $this->action('menu-cliente', 'geral', 'default'); ?>
        <section id="my-account-security-form" class="page container">
            <form id="userSecurityForm" class="form-horizontal" action="<?php echo $this->url(array('module' => 'default', 'controller' => 'minha-conta', 'action' => 'adicionar-endereco'), null, true); ?>" method="post">
                <div class="container">

                    <div class="row">
                        <fieldset>
                            <legend>Cadastro de Endereço</legend><br>
                            <div class="span6">

                                <div class="control-group">
                                    <label class="control-label">CEP:</label>
                                    <div class="controls">
                                        <input name="cep" id="cep" placeholder="00000-000" required="required" class="span4"  type="text">
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label">Endereço:</label>
                                    <div class="controls">
                                        <input name="rua" id="endereco" placeholder="Endereço" required="required" class="span4"  type="text">
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label">Numero:</label>
                                    <div class="controls">
                                        <input name="numero" id="numero" placeholder="Numero"  class="span4"  type="text">
                                    </div>
                                </div>


                            </div>
                            <div  class="span6">

                                <div class="control-group">
                                    <label class="control-label">Bairro:</label>
                                    <div class="controls">
                                        <input name="bairro" id="bairro" placeholder="Bairro" required="required" class="span4"  type="text">
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label">Cidade:</label>
                                    <div class="controls">
                                        <input name="cidade" id="cidade" placeholder="Cidade" required="required" class="span4"  type="text">
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label">Estado:</label>
                                    <div class="controls">
                                        <input name="estado" id="estado" placeholder="Estado" required="required" class="span4"  type="text">
                                    </div>
                                </div>

                            </div>
                        </fieldset>
                    </div>
                    <footer id="submit-actions" class="form-actions">
                        <button id="submit-button" type="submit" class="btn btn-success toltip salvar" title="Salvar Endereço" name="action">Salvar</button>
                        <a href="javascript:history.back()">
                            <button type="button" class="btn toltip" title="Voltar para a pagina anterior" name="action" value="CANCEL">Cancelar</button>
                        </a>
                    </footer>
                </div>
            </form>
        </section>
    </div>