
        <table width="789" height="306" border="0" align="center">
            <tr>
                <th height="79" colspan="2" style="border-bottom: 1px solid #333;
                    border-top: 1px solid #333;" scope="col">
                    <a href="#"></a>
                    <table width="768" border="0" >
                        <tr>
                            <th width="247" height="108" scope="col">
                                <h2><a href="#"><img src="/assets/images/schoeler.png" alt="Insert Logo Here" name="Insert_logo"  id="Insert_logo" style="display:block;" /></a></h2>
                            </th>
                            <th width="498" scope="col"><h2 align="left" style="color:#333;font-size:20px;
                                                            font-weight: bold;">Schoeler Su&iacute;nos</h2>
                              <p align="left" style="color:#333;font-size:20px;
                                                            font-weight: bold;">&nbsp;</p>
                              <p align="justify" style="font-size:12px; color:#666;">Schoeler Suínos - Rodovia PR 151, Km 258, s/n - Machadinho, Piraí do Sul - PR CEP: 84240-000.</p>
                                <p align="justify" style="font-size:12px; color:#666; line-height:1px;">Telefones: (42) 3237-2068 | (42) 3237-3069 | (42) 3237-1058 | (42) 3237-3148</p></th>
                        </tr>
                    </table>
                <p>&nbsp;</p></th>
            </tr>
            <tr>
                <td height="46" colspan="2"><table width="535" border="0" align="center">
                        <tr>
                            <th width="597" scope="col" style="font-size: 16px; text-align:justify;"><p>&nbsp;</p>
                                <p>Confirmação de compra de Suínos tipo abate, proposta de Nº: 1200.</p>
                                <p></p>
                                <p></p>
                                <p>Proposta ofertada em 07/02/2018 11:50:02 por Thiago Carlos e aprovada por Paulo.</p></th>
                        </tr>
              </table></td>
            </tr>
            <tr>
                <td colspan="2"><p>&nbsp;</p>
                    <table width="733" border="1" align="center">
                        <tr>
                            <td width="94"><strong>Comprador:</strong></td>
                            <td width="418">&nbsp;</td>
                        </tr>
                        <tr>
                            <td><strong>Razão Social:</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><strong>CNPJ/CPF:</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><strong>Inscrição Estadual:</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><strong>Endereço:</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><strong>E-mail:</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><strong>Telefone:</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><strong>Responsável:</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                    </table>
                    <p>&nbsp;</p>
                    <table width="733" border="1" align="center">
                        <tr>
                            <td width="94"><strong>Vendedor:</strong></td>
                            <td width="418">&nbsp;</td>
                        </tr>
                        <tr>
                            <td><strong>Razão Social:</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><strong>CNPJ/CPF:</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><strong>Inscrição Estadual:</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><strong>Endereço:</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><strong>E-mail:</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><strong>Telefone:</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td><strong>Responsável:</strong></td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                    </table>
                    <p>&nbsp;</p></td>
            </tr>
            <tr>
                <td width="40">&nbsp;</td>
                <td width="739">&nbsp;</td>
            </tr>
        </table>
       