<?
$this->headScript()->appendFile($this->BaseUrl('assets/area-cliente/js/negociar.js'));
?>
<div id="body-container">
    <div id="body-content">
        <?= $this->action('menu-cliente', 'geral', 'default'); ?>
        <section class="page container">

            <div class="row">
                <div class="span16">
                    <div class="row">

                        <div class="span16">
                            <div class="box pattern pattern-sandstone">
                                <div class="box-header">
                                    <i class="icon-table"></i>
                                    <h5>
                                        Comercialização de Suínos
                                    </h5>
                                </div>
                                <div class="box-content box-table">
                                    <table id="sample-table" class="table table-hover table-bordered tablesorter">
                                        <thead>
                                            <tr>
                                                <th>Produto</th>
                                                <th>Tipo</th>
                                                <th class="td-actions"> Ações</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?
                                            if ($this->vendas) {
                                                foreach ($this->vendas as $row) {
                                                    ?>

                                                    <tr>
                                                        <td><?= ucfirst($row['nome']); ?></td>
                                                        <td><?= ucfirst($row['nome_categoria']); ?></td>
                                                        <td class="td-actions">
                                                            <a href="#" class="btn btn-small btn-info toltip comprar" data-produto="<?= $row['id']; ?>" title="Clique para Comprar">
                                                                <i class="btn-icon-only icon-circle-arrow-down"> Comprar</i>
                                                            </a>
                                                            <!--                                                            <a href="javascript:;" class="btn btn-small btn-danger">
                                                                                                                            <i class="btn-icon-only icon-circle-arrow-up"> Vender</i>
                                                                                                                        </a>-->
                                                        </td>
                                                    </tr>
                                                    <?
                                                }
                                            }
                                            ?>


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </section>
    </div>

    <!-- Modal -->
    <div id="Modal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title titulo">Modal Header</h4>
                </div>
                <div class="modal-body conteudo">
                    <p>Some text in the modal.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger rejeita" param="" data-dismiss="modal">Não Aceito</button>
                    <button type="button" class="btn btn-success aceitar" param="" data-dismiss="modal">Li e aceito o termo de compra</button>
                </div>
            </div>

        </div>
    </div>