<div id="body-container">
    <div id="body-content">
        <?= $this->action('menu-cliente', 'geral', 'default'); ?>

        <section id="my-account-security-form" class="page container">
            <form id="userSecurityForm" class="form-horizontal" action="<?php echo $this->url(array('module' => 'default', 'controller' => 'minha-conta', 'action' => 'negociar'), null, true); ?>" method="post">
                <div class="container">

                    <div class="row">
                        <fieldset>
                            <legend>Negociar com: <?= $this->dados_vendedor['nome']; ?></legend><br>
                            <div class="span5">
                                <input type="hidden" name="produto" value="<?= $this->produto; ?>">
                                <input type="hidden" name="vendedor" value="<?= $this->vendedor; ?>">
                                <div class="control-group ">
                                    <label class="control-label">Quantidade Cabeças (*):</label>
                                    <div class="controls">
                                        <input name="quantidade" class="span3 toltip" title="Insira a quantidade de Suínos" min="60" type="number" required="true" >
                                    </div>
                                </div>

                                <div class="control-group ">
                                    <label class="control-label">Preço K.G (*):</label>
                                    <div class="controls">
                                        <input id="new-pass-control" name="preco" class="span3 preco toltip" title="Insira o preço por Kilo" type="text" required="true">
                                    </div>
                                </div>
                                <div class="control-group ">
                                    <label for="condicao" class="control-label">Condição Pagamento:</label>
                                    <div class="controls">
                                        <select id="condicao" name="condicao_pagamento" class="span3 toltip" title="Insira a condição de pagamento">
                                            <?
                                            if ($this->condicoes) {
                                                foreach ($this->condicoes as $condicao) {
                                                    ?>
                                                    <option value="<?= $condicao['id']; ?>"><?= $condicao['nome']; ?></option>
                                                    <?
                                                }
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </div>

                                <div class="control-group ">
                                    <label for="formas" class="control-label">Forma Pagamento(*):</label>
                                    <div class="controls">
                                        <select id="formas" required="true" name="forma_pagamento" class="span3 toltip" title="Insira a forma de pagamento">
                                            <option value="">Selecione a Forma de Pagamento</option>
                                            <?
                                            if ($this->formas) {
                                                foreach ($this->formas as $formas) {
                                                    ?>
                                                    <option value="<?= $formas['id']; ?>"><?= $formas['nome']; ?></option>
                                                    <?
                                                }
                                            }
                                            ?>
                                        </select>

                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label">Descrição Pagamento:</label>
                                    <div class="controls">
                                        <textarea name="descricao_pagamento" class="span3 toltip" title="Insira alguma informação complementar, referente ao metodo de pagamento!" rows="4" cols="100"></textarea>
                                    </div>
                                </div>

                            </div>
                            <div  class="span5">


                                <div class="control-group ">
                                    <label for="tributacao" class="control-label">Tributação</label>
                                    <div class="controls">
                                        <select id="tributacao" name="tributacao" class="span3 toltip" title="Selecione o tipo de Tributação">
                                            <option value="A negociar">A negociar</option>
                                            <option value="Sem FUNRURAL/sem ICMS">Sem FUNRURAL/sem ICMS</option>
                                            <option value="Sem FUNRURAL/com ICMS">Sem FUNRURAL/com ICMS</option>
                                            <option value="Com FUNRURAL/sem ICMS">Com FUNRURAL/sem ICMS</option>
                                            <option value="Com FUNRURAL/com ICMS">Com FUNRURAL/com ICMS</option>
                                        </select>

                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label">Descrição Tributária:</label>
                                    <div class="controls">
                                        <textarea name="descricao_tributaria" class="span3 toltip" title="Insira alguma informação complementar referente a tributação" rows="6" cols="100"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div  class="span5">

                                <div class="control-group ">
                                    <label class="control-label">Data Entrega (*):</label>
                                    <div class="controls">
                                        <input id="challenge-answer-control" name="data_entrega" class="span3 toltip" title="Insira a data de entrega da carga!" type="date" value="" required="true">
                                    </div>
                                </div>

                                <div class="control-group ">
                                    <label class="control-label">Horário Recebimento (*):</label>
                                    <div class="controls">
                                        <input  name="hora_inicial" class="span3 toltip" title="Insira o horario inicial de recebimento de suínos." type="time" value="" required="true">
                                    </div>
                                </div>

                                <div class="control-group ">
                                    <label class="control-label">Horário Final (*):</label>
                                    <div class="controls">
                                        <input  name="hora_final" class="span3 toltip" title="Insira o horario final de recebimento de suínos." type="time" value="" required="true">
                                    </div>
                                </div>

                                <div class="control-group ">
                                    <label for="endereco" class="control-label">Endereço Entrega (*):</label>
                                    <div class="controls">
                                        <select id="endereco" required="true" name="endereco" class="span3 toltip" title="Selecione o endereço do frigorífico, para a entrega">
                                            <option value="">Selecione o Endereço</option>
                                            <?
                                            if ($this->enderecos) {
                                                foreach ($this->enderecos as $endereco) {
                                                    ?>
                                                    <option value="<?= $endereco['id']; ?>"><?= $endereco['rua']; ?> - <?= $endereco['cidade']; ?> - <?= $endereco['estado']; ?></option>
                                                    <?
                                                }
                                            }
                                            ?>
                                            ?>

                                        </select>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label">Comentários:</label>
                                    <div class="controls">
                                        <textarea name="comentario" class="span3 toltip" title="Insira alguma informação complementar" rows="4" cols="100"></textarea>
                                    </div>
                                </div>

                            </div>
                        </fieldset>
                    </div>
                    <footer id="submit-actions" class="form-actions">
                        <button id="submit-button" type="submit" class="btn btn-primary toltip" title="Enviar Proposta" name="action">Enviar</button>
                        <a href="javascript:history.back()" class="toltip" title="Voltar para a pagina anterior">
                            <button type="button" class="btn" name="action" value="CANCEL">Cancelar</button>
                        </a>
                    </footer>
                </div>
            </form>
        </section>
    </div>