<div id="body-container">
    <div id="body-content">
        <?= $this->action('menu-cliente', 'geral', 'default'); ?>
        <section class="page container">

            <div class="row">
                <div class="span16">
                    <div class="row">

                        <div class="span16">
                            <div class="box pattern pattern-sandstone">
                                <div class="box-header">
                                    <i class="icon-table"></i>
                                    <h5>
                                        Comercialização de Suínos
                                    </h5>
                                </div>
                                <div class="box-content box-table">
                                    <table id="sample-table" class="table table-hover table-bordered tablesorter">
                                        <thead>
                                            <tr>
                                                <th>Produto</th>
                                                <th>Tipo</th>
                                                <th>Quantidade</th>
                                                <th>Unidade</th>
                                                <th>Vendedor</th>
                                                <th>Status</th>
                                                <th class="td-actions"> Ações</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?
                                            if ($this->dados) {
                                                foreach ($this->dados as $row) {
                                                    ?>

                                                    <tr>
                                                        <td><?= ucfirst($row['nome_item']); ?></td>
                                                        <td><?= ucfirst($row['nome_categoria']); ?></td>
                                                        <td><?= $row['quantidade']; ?></td>
                                                        <td><?= $row['unidade']; ?></td>
                                                        <td><?= $row['nome_vendedor']; ?></td>
                                                        <td><?
                                                            if ($row['status'] == 1) {
                                                                echo 'Aguardando Proposta Vendedor';
                                                            } elseif ($row['status'] == 2) {
                                                                echo 'Aguardando Sua Resposta';
                                                            } elseif ($row['status'] == 3) {
                                                                echo 'Aprovada';
                                                            } elseif ($row['status'] == 4) {
                                                                echo 'Cancelado';
                                                            }
                                                            ?>
                                                        </td>
                                                        <td class="td-actions">
                                                            <? if ($row['status'] != '4') { ?>
                                                                <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'minha-conta', 'action' => 'visualiza-negociacao', 'negociacao' => $row['id']), null, true); ?>" class="btn btn-small btn-info toltip" title="Visualizar Propostas">
                                                                    <i class="btn-icon-only icon-eject"> Visualizar</i>
                                                                </a>
                                                                <? if ($row['status'] == '2') { ?>
                                                                    <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'minha-conta', 'action' => 'aprovar-negociacao', 'negociacao' => $row['id']), null, true); ?>" class="btn btn-small btn-info toltip" title="Aprovar Proposta">
                                                                        <i class="btn-icon-only icon-check"> Aprovar</i>
                                                                    </a>
                                                                <? } ?>

                                                                <? if ($row['status'] == '2') { ?>
                                                                    <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'minha-conta', 'action' => 'fazer-negociacao', 'negociacao' => $row['id']), null, true); ?>" class="btn btn-small btn-info toltip" title="Fazer Contraproposta">
                                                                        <i class="btn-icon-only icon-map-marker"> Fazer Proposta</i>
                                                                    </a>
                                                                <? } ?>

                                                                <? if ($row['status'] == '3' && $row['faturamento'] > '0') { ?>
                                                                    <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'minha-conta', 'action' => 'comprovante-baixar', 'negociacao' => $row['id']), null, true); ?>" class="btn btn-small btn-info toltip" title="Baixar comprovante de Compra">
                                                                        <i class="btn-icon-only icon-download"> Download Comprovante</i>
                                                                    </a>
                                                                <? } ?>

                                                                <? if ($row['status'] != '3') { ?>
                                                                    <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'minha-conta', 'action' => 'cancelar-negociacao', 'negociacao' => $row['id']), null, true); ?>" class="btn btn-small btn-info toltip" title="Cancelar Negociação">
                                                                        <i class="btn-icon-only icon-remove"> Cancelar</i>
                                                                    </a>
                                                                <? } ?>
                                                            <? } ?>
                                                        </td>
                                                    </tr>
                                                    <?
                                                }
                                            } else {
                                                ?>
                                            <p></p>
                                            <p></p>
                                            <div class="alert alert-info"><strong>Não</strong> há Registros!</div>
                                        <? } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </section>
    </div>