<div id="body-container">
    <div id="body-content">
        <?= $this->action('menu-cliente', 'geral', 'default'); ?>
        <section class="page container">

            <div class="row">
                <div class="span16">
                    <div class="row">

                        <div class="span16">
                            <div class="box pattern pattern-sandstone">
                                <div class="box-header">
                                    <i class="icon-table"></i>
                                    <h5>
                                        Com qual vendedor deseja negociar?
                                    </h5>
                                </div>
                                <div class="box-content box-table">
                                    <table id="sample-table" class="table table-hover table-bordered tablesorter">
                                        <thead>
                                            <tr>
                                                <th>Nome</th>
                                                <th>E-mail</th>
                                                <th>Telefone</th>
                                                <th class="td-actions"> Negociar</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?
                                            if ($this->vendedores) {
                                                foreach ($this->vendedores as $row) {
                                                    ?>

                                                    <tr>
                                                        <td><?= ucfirst($row['nome']); ?></td>
                                                        <td>
                                                            <a href="mailto:<?= $row['email']; ?>">
                                                                <?= $row['email']; ?>
                                                            </a>
                                                        </td>
                                                        <td><?= $row['telefone']; ?></td>

                                                        <td class="td-actions">
                                                            <a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'minha-conta', 'action' => 'negociar', 'produto' => $row['produto'], 'vendedor' => $row['vendedor']), null, true); ?>" class="btn btn-small btn-info">
                                                                <i class="btn-icon-only icon-circle-arrow-down toltip" title="Fazer proposta para o vendedor: <?= ucfirst($row['nome']); ?>"> Negociar</i>
                                                            </a>

                                                        </td>
                                                    </tr>
                                                    <?
                                                }
                                            }
                                            ?>


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </section>
    </div>